/**
 * Códigos de erro padronizados conforme SPECS.md Seção 4.2
 */

export const AUTH_ERRORS = {
    INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
    TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
    TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
    REFRESH_EXPIRED: 'AUTH_REFRESH_EXPIRED',
    REFRESH_REVOKED: 'AUTH_REFRESH_REVOKED',
    ACCOUNT_DISABLED: 'AUTH_ACCOUNT_DISABLED',
    ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
    INSUFFICIENT_ROLE: 'AUTH_INSUFFICIENT_ROLE',
    TENANT_MISMATCH: 'AUTH_TENANT_MISMATCH',
} as const;

export const VALIDATION_ERRORS = {
    FAILED: 'VALIDATION_FAILED',
    REQUIRED_FIELD: 'VALIDATION_REQUIRED_FIELD',
    INVALID_FORMAT: 'VALIDATION_INVALID_FORMAT',
    OUT_OF_RANGE: 'VALIDATION_OUT_OF_RANGE',
    INVALID_ENUM: 'VALIDATION_INVALID_ENUM',
    STRING_TOO_LONG: 'VALIDATION_STRING_TOO_LONG',
    INVALID_UUID: 'VALIDATION_INVALID_UUID',
    INVALID_DATE: 'VALIDATION_INVALID_DATE',
} as const;

export const RESOURCE_ERRORS = {
    NOT_FOUND: 'RESOURCE_NOT_FOUND',
    ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',
    DELETED: 'RESOURCE_DELETED',
    CONFLICT: 'RESOURCE_CONFLICT',
} as const;

export const BARREL_ERRORS = {
    NOT_FOUND: 'BARREL_NOT_FOUND',
    QR_CODE_EXISTS: 'BARREL_QR_CODE_EXISTS',
    INVALID_STATUS_TRANSITION: 'BARREL_INVALID_STATUS_TRANSITION',
    NOT_READY_FOR_EXPEDITION: 'BARREL_NOT_READY_FOR_EXPEDITION',
    NOT_IN_TRANSIT: 'BARREL_NOT_IN_TRANSIT',
    NOT_AT_CLIENT: 'BARREL_NOT_AT_CLIENT',
    BLOCKED_CRITICAL_COMPONENT: 'BARREL_BLOCKED_CRITICAL_COMPONENT',
    BLOCKED: 'BARREL_BLOCKED',
    DISPOSED: 'BARREL_DISPOSED',
} as const;

export const MAINTENANCE_ERRORS = {
    ORDER_NOT_FOUND: 'MAINTENANCE_ORDER_NOT_FOUND',
    ORDER_ALREADY_COMPLETED: 'MAINTENANCE_ORDER_ALREADY_COMPLETED',
    ORDER_CANCELLED: 'MAINTENANCE_ORDER_CANCELLED',
    INVALID_COMPONENT: 'MAINTENANCE_INVALID_COMPONENT',
    PRESSURE_TEST_REQUIRED: 'MAINTENANCE_PRESSURE_TEST_REQUIRED',
} as const;

export const ALERT_ERRORS = {
    NOT_FOUND: 'ALERT_NOT_FOUND',
    ALREADY_RESOLVED: 'ALERT_ALREADY_RESOLVED',
    CANNOT_ACKNOWLEDGE: 'ALERT_CANNOT_ACKNOWLEDGE',
} as const;

export const GEOFENCE_ERRORS = {
    NOT_FOUND: 'GEOFENCE_NOT_FOUND',
    VIOLATION: 'GEOFENCE_VIOLATION',
    OVERLAPPING: 'GEOFENCE_OVERLAPPING',
} as const;

export const RATE_ERRORS = {
    LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
    AUTH_LIMIT: 'RATE_LIMIT_AUTH',
    EXPORT_LIMIT: 'RATE_LIMIT_EXPORT',
} as const;

export const SYSTEM_ERRORS = {
    INTERNAL_ERROR: 'SYSTEM_INTERNAL_ERROR',
    SERVICE_UNAVAILABLE: 'SYSTEM_SERVICE_UNAVAILABLE',
    DATABASE_ERROR: 'SYSTEM_DATABASE_ERROR',
    EXTERNAL_SERVICE_ERROR: 'SYSTEM_EXTERNAL_SERVICE_ERROR',
} as const;

export const ALERT_TYPES = {
    COMPONENT_HEALTH_YELLOW: 'COMPONENT_HEALTH_YELLOW',
    COMPONENT_END_OF_LIFE: 'COMPONENT_END_OF_LIFE',
    BARREL_IDLE_AT_CLIENT: 'BARREL_IDLE_AT_CLIENT',
    BARREL_IDLE_AT_FACTORY: 'BARREL_IDLE_AT_FACTORY',
    GEOFENCE_VIOLATION: 'GEOFENCE_VIOLATION',
    GPS_DEVICE_OFFLINE: 'GPS_DEVICE_OFFLINE',
    UNAUTHORIZED_MOVEMENT: 'UNAUTHORIZED_MOVEMENT',
    MAINTENANCE_OVERDUE: 'MAINTENANCE_OVERDUE',
    BARREL_LOST: 'BARREL_LOST',
    CRITICAL_COMPONENT_EXPIRED: 'CRITICAL_COMPONENT_EXPIRED',
} as const;
